### ISSUE TITLE
TorrentCleanup.py not working on Radarr v3

### ISSUE THREAD

**Issue by sevospl** [Cloudbox/Cloudbox#406]
Using Radarr v3 from hotio (aphrodite tag). TorrentCleanup.py script is not working:

```
2020-6-12 11:49:05.9|Debug|CustomScript|Executing external script: /scripts/torrents/TorrentCleanup.py
2020-6-12 11:49:05.9|Trace|ProcessProvider|Setting environment variable 'radarr_eventtype' to 'Test'
2020-6-12 11:49:05.9|Debug|TorrentCleanup.py|Starting /scripts/torrents/TorrentCleanup.py 
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|Traceback (most recent call last):
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|  File "/scripts/torrents/TorrentCleanup.py", line 47, in <module>
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|    if os.path.exists(sourceFile) and os.path.isfile(sourceFile):
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|    os.stat(path)
2020-6-12 11:49:06.0|Error|TorrentCleanup.py|TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
2020-6-12 11:49:06.0|Debug|CustomScript|Executed external script: /scripts/torrents/TorrentCleanup.py - Status: 1
2020-6-12 11:49:06.0|Debug|CustomScript|Script Output: 
6/12/2020 9:49:06 AM - Error - Traceback (most recent call last):
6/12/2020 9:49:06 AM - Error -   File "/scripts/torrents/TorrentCleanup.py", line 47, in <module>
6/12/2020 9:49:06 AM - Error -     if os.path.exists(sourceFile) and os.path.isfile(sourceFile):
6/12/2020 9:49:06 AM - Error -   File "/usr/lib/python3.8/genericpath.py", line 19, in exists
6/12/2020 9:49:06 AM - Error -     os.stat(path)
6/12/2020 9:49:06 AM - Error - TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
2020-6-12 11:49:06.0|Trace|RadarrErrorPipeline|Handling Exception
2020-6-12 11:49:06.0|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1
```

**Comment by sevospl** [comment]
Thanks @Migz93 for the help on Discord. Turned out that TorrentCleanup already has support for the test event but it's not merged into `master` yet. I manually grabbed and it's all good now.

@l3uddz or @desimaniac you probably want to merge it by now.
