### ISSUE TITLE
Broken nzbhydra2 - 502 error

### ISSUE THREAD

**Issue by VindicoRory** [Cloudbox/Cloudbox#480]
**Describe the bug**
I am currently in the process of installing Cloudbox to a machine, currently on the NZBHydra2 setup step and the furthest I can get is a `502 Bad Gateway` screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/89988782/168590388-07a5243a-e30a-4917-ab60-a812a95e5286.png)

**Logs**
Docker Log Output:
```
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1001
PGID=1002
UMASK=002
TZ=GB
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Logging wrapper output to /config/logs/wrapper.log
2022-05-16 13:11:46,232  INFO - Determined java version as '11' from version string 'openjdk version "11.0.15" 2022-04-19'
2022-05-16 13:11:46,232  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/bin/lib/core-4.3.1-exec.jar --nobrowser --datafolder /config in folder /app/bin
13:11:46.657 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file /config/nzbhydra.yml.bak
 at [Source: (File); line: 1, column: 1]
java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.
        at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:247)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
Caused by: java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.
        at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:247)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
2022-05-16 13:11:46,668  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Attempted Fix**
I have attempted the fix mentioned in issue #434 to get the same result.

**System Information**

 - Cloudbox Version: Develop (latest)
 - Operating System: Ubuntu Server 18.04 LTS
 - Linux Kernel: 5.4.0-110-generic

**Comment by owine** [comment]
Your config is corrupted as the logs state. Restoring a previous backup of the config should restore a working state. Please do not use GitHub for support. You may join the Discord for support.

**Comment by VindicoRory** [comment]
I understand this, the reason I am reporting this as a bug is the fact, like I said in the initial issue, that this is a fresh install so there is no "working state". I was wondering if this was an issue in the Ansible installer script.
